# Generated by Django 5.2.4 on 2025-08-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_title_alter_library_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ligrarian',
            new_name='Librarian',
        ),
    ]
